### Тестирование поиска книг по названию
PUT http://book-library-fedyancev.ru:8082/books?title=Мечтают ли андройды об электроовцах?

> {%
  client.test('Тестирование поиска книги по названию', function () {
   client.assert(response.status === 200, 'Проверяю код ответа. Фактическое знаение: ' + response.status);
   client.assert(response.body === "Hello", 'Валидный ответ');
 });
 %}

Сценарий №1
HTTP запрос
	PUT http://spisok-kontaktov.ru:80/contact_list/1 HTTP/1.1

	{ "blacklist" : true}

HTTP ответ
	HTTP/1.1 200 OK

	Успешно

Сценарий №2
HTTP запрос
	GET http://spisok-kontaktov.ru:80/address/1


HTTP ответ
	HTTP/1.1 200 OK
	Content-Type: application/json; charset=utf-8

	id , id_recipient , id_address


















