--
-- PostgreSQL database dump
--

-- Dumped from database version 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
-- Dumped by pg_dump version 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP INDEX public.users_login_unq;
DROP INDEX public.text_documents_year_idx;
DROP INDEX public.text_documents_type_idx;
DROP INDEX public.text_documents_title_idx;
DROP INDEX public.text_document_to_author_text_document_id_idx;
DROP INDEX public.text_document_to_author_text_document_id_author_id_idx;
DROP INDEX public.text_document_to_author_author_id_idx;
DROP INDEX public.text_document_status_name_unq;
DROP INDEX public.currency_name_unq;
DROP INDEX public.currency_code_unq;
DROP INDEX public.country_code_unq;
DROP INDEX public.country_code3_unq;
DROP INDEX public.country_code2_idx;
DROP INDEX public.authors_surname_idx;
ALTER TABLE ONLY public.users DROP CONSTRAINT user_id_pk;
ALTER TABLE ONLY public.text_documents DROP CONSTRAINT text_documents_id_pk;
ALTER TABLE ONLY public.text_document_status DROP CONSTRAINT text_document_status_pkey;
ALTER TABLE ONLY public.purchase_price DROP CONSTRAINT purchase_price_pkey;
ALTER TABLE ONLY public.currency DROP CONSTRAINT currency_pkey;
ALTER TABLE ONLY public.country DROP CONSTRAINT country_pkey;
ALTER TABLE ONLY public.authors DROP CONSTRAINT authors_pk;
DROP TABLE public.users;
DROP TABLE public.text_documents;
DROP TABLE public.text_document_to_author;
DROP TABLE public.text_document_status;
DROP TABLE public.purchase_price;
DROP TABLE public.currency;
DROP TABLE public.country;
DROP TABLE public.authors;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: authors; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authors (
    id integer NOT NULL,
    name character varying(255),
    surname character varying(255),
    birthday date,
    country_id integer NOT NULL
);


ALTER TABLE public.authors OWNER TO postgres;

--
-- Name: authors_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.authors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authors_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: country; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.country (
    id integer NOT NULL,
    code2 character varying(2) NOT NULL,
    code3 character varying(3) NOT NULL,
    code character varying(3) NOT NULL,
    name character varying(100) NOT NULL
);


ALTER TABLE public.country OWNER TO postgres;

--
-- Name: country_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.country ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.country_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: currency; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.currency (
    id integer NOT NULL,
    code integer NOT NULL,
    name character varying(3) NOT NULL,
    description character varying(255) NOT NULL
);


ALTER TABLE public.currency OWNER TO postgres;

--
-- Name: currency_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.currency ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.currency_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: purchase_price; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.purchase_price (
    text_document_id integer,
    date timestamp without time zone,
    price integer,
    id integer NOT NULL,
    currency_id integer NOT NULL
);


ALTER TABLE public.purchase_price OWNER TO postgres;

--
-- Name: purchase_price_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.purchase_price ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.purchase_price_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: text_document_status; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.text_document_status (
    id integer NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.text_document_status OWNER TO postgres;

--
-- Name: text_document_status_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.text_document_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.text_document_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: text_document_to_author; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.text_document_to_author (
    text_document_id integer NOT NULL,
    author_id integer NOT NULL
);


ALTER TABLE public.text_document_to_author OWNER TO postgres;

--
-- Name: text_documents; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.text_documents (
    id integer NOT NULL,
    title character varying(255),
    year date,
    type character varying(30),
    number integer,
    status_id integer
);


ALTER TABLE public.text_documents OWNER TO postgres;

--
-- Name: text_documents_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.text_documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.text_documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    login character varying(50),
    password character varying(60)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authors authors_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authors
    ADD CONSTRAINT authors_pk PRIMARY KEY (id);


--
-- Name: country country_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.country
    ADD CONSTRAINT country_pkey PRIMARY KEY (id);


--
-- Name: currency currency_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.currency
    ADD CONSTRAINT currency_pkey PRIMARY KEY (id);


--
-- Name: purchase_price purchase_price_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.purchase_price
    ADD CONSTRAINT purchase_price_pkey PRIMARY KEY (id);


--
-- Name: text_document_status text_document_status_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.text_document_status
    ADD CONSTRAINT text_document_status_pkey PRIMARY KEY (id);


--
-- Name: text_documents text_documents_id_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.text_documents
    ADD CONSTRAINT text_documents_id_pk PRIMARY KEY (id);


--
-- Name: users user_id_pk; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT user_id_pk PRIMARY KEY (id);


--
-- Name: authors_surname_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authors_surname_idx ON public.authors USING btree (surname);


--
-- Name: country_code2_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX country_code2_idx ON public.country USING btree (code2);


--
-- Name: country_code3_unq; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX country_code3_unq ON public.country USING btree (code3);


--
-- Name: country_code_unq; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX country_code_unq ON public.country USING btree (code);


--
-- Name: currency_code_unq; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX currency_code_unq ON public.currency USING btree (code);


--
-- Name: currency_name_unq; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX currency_name_unq ON public.currency USING btree (name);


--
-- Name: text_document_status_name_unq; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX text_document_status_name_unq ON public.text_document_status USING btree (name);


--
-- Name: text_document_to_author_author_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX text_document_to_author_author_id_idx ON public.text_document_to_author USING btree (author_id);


--
-- Name: text_document_to_author_text_document_id_author_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX text_document_to_author_text_document_id_author_id_idx ON public.text_document_to_author USING btree (text_document_id, author_id);


--
-- Name: text_document_to_author_text_document_id_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX text_document_to_author_text_document_id_idx ON public.text_document_to_author USING btree (text_document_id);


--
-- Name: text_documents_title_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX text_documents_title_idx ON public.text_documents USING btree (title);


--
-- Name: text_documents_type_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX text_documents_type_idx ON public.text_documents USING btree (type);


--
-- Name: text_documents_year_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX text_documents_year_idx ON public.text_documents USING btree (year);


--
-- Name: users_login_unq; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX users_login_unq ON public.users USING btree (login);


--
-- PostgreSQL database dump complete
--

